# Generated by Django 3.2.15 on 2022-08-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodeguero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('exp_laboral', models.CharField(max_length=50)),
                ('idiomas', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('creat_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('exp_laboral', models.CharField(max_length=50)),
                ('idiomas', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('creat_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('bodeguero', models.CharField(max_length=100)),
                ('creat_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('cajero', models.CharField(max_length=100)),
                ('creat_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(max_length=200, null=True)),
                ('precio_unitario', models.FloatField(max_length=200, null=True)),
                ('importe', models.FloatField(max_length=200, null=True)),
                ('subtotal', models.FloatField(max_length=200, null=True)),
                ('iva', models.FloatField(max_length=200, null=True)),
                ('total', models.FloatField(max_length=200, null=True)),
                ('factura', models.FloatField(max_length=200, null=True)),
                ('producto', models.FloatField(max_length=200, null=True)),
                ('creat_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=100)),
                ('cajero', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('creat_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_actual', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('descuento', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('creat_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('creat_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
