# Generated by Django 3.2.15 on 2022-08-14 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodeguero',
            old_name='exp_laboral',
            new_name='tipo_de_licencia',
        ),
        migrations.RemoveField(
            model_name='bodeguero',
            name='idiomas',
        ),
    ]
